# ntroller_manager:
#   ros__parameters:
#     update_rate: 10  # Hz

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

#     forward_position_controller:
#       type: forward_command_controller/ForwardCommandController

#     position_trajectory_controller:
#       type: joint_trajectory_controller/JointTrajectoryController


# forward_position_controller:
#   ros__parameters:
#     joints:
#       - rear_left_wheel_joint
#       - rear_righ_wheel_joint
#     interface_name: position


# position_trajectory_controller:
#   ros__parameters:
#     joints:
#       - rear_left_wheel_joint
#       - rear_righ_wheel_joint

#     command_interfaces:
#       - position

#     state_interfaces:
#       - position

#     state_publish_rate: 200.0 # Defaults to 50
#     action_monitor_rate: 20.0 # Defaults to 20

#     allow_partial_joints_goal: false # Defaults to false
#     open_loop_control: true
#     allow_integration_in_goal_trajectories: true
#     constraints:
#       stopped_velocity_tolerance: 0.01 # Defaults to 0.01
#       goal_time: 0.0 # Defaults to 0.0 (start immediately)


# # controller_manager:
# #   ros__parameters:
# #     update_rate: 30
# #     use_sim_time: true

# #     # Define the diff drive controller
# #     diff_drive_controller:
# #       type: diff_drive_controller/DiffDriveController  # This is the key missing part
# #       publish_rate: 50.0
# #       base_frame_id: base_link
# #       left_wheel_names: ['rear_left_wheel_joint']
# #       right_wheel_names: ['rear_right_wheel_joint']
# #       wheel_separation: 0.6
# #       wheel_radius: 0.1
# #       use_stamped_vel: false

# #     # Define the joint state broadcaster
# #     joint_state_broadcaster:
# #       type: joint_state_broadcaster/JointStateBroadcaster


controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    # Correct name: diff_drive_controller
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


diff_drive_controller:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['front_left_wheel_joint', 'rear_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'rear_right_wheel_joint']
    wheel_separation: 0.6
    wheel_radius: 0.1

    use_stamped_vel: false




    # Add remapping here
    # cmd_vel_topic: '/cmd_vel'  # Remap cmd_vel_unstamped to cmd_vel
    # odom_topic: '/odom'        # Remap odom topic to /odom

